alias sinst="sudo apt-get update && sudo apt-get -s install"
alias inst="sudo apt-get update && sudo apt-get install"
alias srem="sudo apt-get -s purge"
alias rem="sudo apt-get purge"

alias ..="cd .."

alias ls="ls --color=auto -F -h"
alias l="ls -1"
alias la="l -A"
alias ll="ls -l"
alias lal="ls -Al"
alias lc="ls"
alias lca="ls -A"

alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

alias diff="diff --color=auto"

alias g="git"
alias ga="g add"
alias gc="g commit"
alias gd="g diff"
alias gds="gd --staged"
alias gf="g fetch"
alias gl="g log --graph --date='format:%Y-%m-%d %H:%M' --pretty='format:%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s'"
alias gp="g pull"
alias gs="g status"
