set background=dark
set t_Co=256             " 256 colors
syntax on
colorscheme solarized

" custom color for listchars (trailing spaces and tabs)
highlight SpecialKey cterm=NONE ctermbg=NONE ctermfg=244 gui=NONE guibg=NONE guifg=#839496

set encoding=utf8        " set utf8 as standard encoding

set complete+=kspell     " word completion
set completeopt=menuone  " show completion menu even if there's only one match
set completeopt+=longest " insert only longest common text of all matches

set wildmenu             " command-line completion menu
set wildignorecase       " ignore case when completing file names and directories

set history=50
set nobackup             " no backup files
set viminfo+=n~/.vim/viminfo " viminfo file inside ~/.vim

set scrolloff=3          " scroll lines offset using j/k
set relativenumber       " numbers are relative to current line

set ignorecase           " ignore case when searching
set smartcase            " but become case sensitive if there are uppercase characters
set hlsearch             " highlights search results
set incsearch            " incremental search
set magic                " change the way backslashes are used in search patterns

set textwidth=80         " max line width
set colorcolumn=81       " highlights 81th column
set cursorline           " highlights current line

set splitbelow           " open horizontal split below
set splitright           " open vertical split on the right

set expandtab            " spaces instead of tabs
set tabstop=8            " 1 tab == 8 spaces
set autoindent
set smarttab             " smart tab handling for indenting
set shiftwidth=8         " spaces for autoindent
set list                 " needed to get listchars working
set listchars=trail:-,tab:▸\  " show trailing spaces as - and tabs as ▸

filetype plugin indent on

set formatoptions+=j     " remove a comment leader when joining lines

set ruler                " show line and column number of the cursor position
set laststatus=2         " always show statusline

set lazyredraw           " do not redraw screen in the middle of a macro

" go wants tabs
autocmd Filetype go setlocal noexpandtab

" return to last edit position when opening files
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

" MakeTags creates the "tags" file (ctags must be installed)
command! MakeTags !ctags -R .

" make this line a (nice) markdown header
command H1 normal yypVr=2o<ESC>
command H2 normal yypVr-2o<ESC>

" toggle paste mode
set pastetoggle=<F2>

" turn off highlighting after a search
map <F3> :nohlsearch<CR>

" open files explorer
map <F4> :Explore<CR>

" toggle spell checker
map <F5> :setlocal spell! spelllang=en_us<CR>

" list buffers and prepare for switching
map gb :buffers<CR>:b

let g:netrw_banner=0                                " hide banner
let g:netrw_liststyle=3                             " tree view
let g:netrw_bufsettings='noma nomod nobl nowrap ro' " keep relative numbers

let g:hardtime_default_on=1     " hardtime on by default
